name: ip_remote
description: A new Flutter project.

version: 1.1.1+4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+1
  rxdart: ^0.21.0
  sqflite: ^1.1.3
  flutter_material_color_picker: ^0.0.5
  flutter_reorderable_list: ^0.1.3
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: OxygenMono
      fonts:
      - asset: fonts/OxygenMono-Regular.ttf

  uses-material-design: true
